#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-model-deployment
spec:
  selector:
    matchLabels:
      app: my-model-server
  replicas: 1
  template:
    metadata:
      labels:
        app: my-model-server
    spec:
      containers:
      - name: my-model-container
        image: docker.io/{docker_user}/{model_name}:{github.sha} 
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-model-service
  name: my-model-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: my-model-server
  type: LoadBalancer
