#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimodelo-deployment
spec:
  selector:
    matchLabels:
      app: mimodelo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mimodelo-server
    spec:
      containers:
      - name: mimodelo-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/sergiojc/my-model 
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mimodelo-service
  name: mimodelo-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: mimodelo-server
  type: ClusterIP
